Repository openshift/source-to-image, pull requests merged in 2018-04, with the labels that each got.

#861 update the dep checker to check glide instead of godep files
  CONTRIBUTING.md
  hack/verify-deps.sh
  tools/depchecker/godepchecker.go
  tools/godepchecker/godepchecker.go
Labels: size/L

#869 fix s2i tests
  hack/test-stirunimage.sh
Labels: size/S

#868 Fix comment in godepchecker
  tools/depchecker/godepchecker.go
Labels: size/XS
