Repository openshift/source-to-image, pull requests merged in 2018-05, with the labels that each got.

#875 Fixing tar unit test on macOS
  pkg/tar/tar_test.go
Labels: size/XS

#873 Parse multiple volumes via semicolon delimeter.
  hack/test-stirunimage.sh
  pkg/api/types.go
  pkg/api/types_test.go
  test/integration/integration_test.go
Labels: size/M

#874 Improve URL redaction
  pkg/util/env.go
  pkg/util/env_test.go
Labels: size/M

#866 Keep Option for Injected Files
  pkg/api/types.go
  pkg/build/strategies/sti/sti.go
  pkg/util/injection.go
  pkg/util/injection_test.go
  test/integration/integration_test.go
Labels: size/L

#878 Option to produce a buildable Dockerfile instead of an image when building
  contrib/completions/bash/s2i
  contrib/completions/zsh/s2i
  hack/test-stirunimage.sh
  pkg/api/scripts.go
  pkg/api/types.go
  pkg/build/strategies/dockerfile/dockerfile.go
  pkg/build/strategies/onbuild/onbuild.go
  pkg/build/strategies/sti/sti.go
  pkg/build/strategies/sti/sti_test.go
  pkg/build/strategies/strategies.go
  pkg/cmd/cli/cmd/build.go
  pkg/scripts/environment.go
  pkg/scripts/install.go
  pkg/scripts/install_test.go
  pkg/util/labels.go
  pkg/util/user/rangelist.go
  test/integration/integration_test.go
Labels: size/XL

#879 Check Assemble Users Against Allowed UIDs
  hack/build-test-images.sh
  hack/test-integration.sh
  pkg/api/describe/describer.go
  pkg/build/strategies/sti/sti.go
  pkg/build/strategies/strategies.go
  pkg/cmd/cli/cmd/rebuild.go
  pkg/docker/util.go
  pkg/docker/util_test.go
  pkg/errors/errors.go
  test/integration/images/sti-fake-assemble-root/Dockerfile
  test/integration/images/sti-fake-assemble-user/Dockerfile
  test/integration/integration_test.go
Labels: lgtm, size/L

#883 [3.10] Check Assemble Users Against Allowed UIDs
  hack/build-test-images.sh
  hack/test-integration.sh
  pkg/api/describe/describer.go
  pkg/build/strategies/sti/sti.go
  pkg/build/strategies/strategies.go
  pkg/cmd/cli/cmd/rebuild.go
  pkg/docker/util.go
  pkg/docker/util_test.go
  pkg/errors/errors.go
  test/integration/images/sti-fake-assemble-root/Dockerfile
  test/integration/images/sti-fake-assemble-user/Dockerfile
  test/integration/integration_test.go
Labels: size/L

#884 [3.9] Check Assemble Users Against Allowed UIDs
  hack/build-test-images.sh
  hack/test-integration.sh
  hack/test-stirunimage.sh
  pkg/api/describe/describer.go
  pkg/build/strategies/sti/sti.go
  pkg/build/strategies/strategies.go
  pkg/cmd/cli/cmd/rebuild.go
  pkg/docker/util.go
  pkg/docker/util_test.go
  pkg/errors/errors.go
  test/integration/images/sti-fake-assemble-root/Dockerfile
  test/integration/images/sti-fake-assemble-user/Dockerfile
  test/integration/integration_test.go
Labels: size/L

#885 [3.7] Check Assemble Users Against Allowed UIDs
  hack/build-test-images.sh
  hack/test-integration.sh
  hack/test-stirunimage.sh
  pkg/api/describe/describer.go
  pkg/build/strategies/sti/sti.go
  pkg/build/strategies/strategies.go
  pkg/cmd/cli/cmd/rebuild.go
  pkg/docker/util.go
  pkg/docker/util_test.go
  pkg/errors/errors.go
  test/integration/images/sti-fake-assemble-root/Dockerfile
  test/integration/images/sti-fake-assemble-user/Dockerfile
  test/integration/integration_test.go
Labels: size/L

#886 [3.9] prevent save-artifact tar extraction from overwriting files out…
  pkg/build/strategies/sti/sti.go
  pkg/tar/tar.go
Labels: size/M

#887 [3.7] prevent save-artifact tar extraction from overwriting files out…
  pkg/build/strategies/sti/sti.go
  pkg/tar/tar.go
Labels: size/M
