Repository openshift/source-to-image, pull requests merged in 2018-06, with the labels that each got.

#891 Update build flags in cli doc
  docs/cli.md
Labels: size/M

#894 fix image repository name
  docs/cli.md
Labels: size/XS

#895 add godoc to make govet happy
  pkg/build/strategies/sti/sti.go
Labels: size/XS

#890 Constants package
  pkg/api/constants/doc.go
  pkg/api/constants/env.go
  pkg/api/constants/labels.go
  pkg/api/constants/scripts.go
  pkg/api/types.go
  pkg/build/config.go
  pkg/build/strategies/dockerfile/dockerfile.go
  pkg/build/strategies/layered/layered.go
  pkg/build/strategies/layered/layered_test.go
  pkg/build/strategies/onbuild/onbuild.go
  pkg/build/strategies/sti/postexecutorstep.go
  pkg/build/strategies/sti/sti.go
  pkg/build/strategies/sti/sti_test.go
  pkg/build/strategies/sti/usage.go
  pkg/build/strategies/sti/usage_test.go
  pkg/docker/docker.go
  pkg/docker/docker_test.go
  pkg/docker/util.go
  pkg/docker/util_test.go
  pkg/errors/errors.go
  pkg/ignore/ignore.go
  pkg/ignore/ignore_test.go
  pkg/scm/downloaders/file/download.go
  pkg/scm/downloaders/git/clone.go
  pkg/scripts/environment.go
  pkg/scripts/install.go
  pkg/scripts/install_test.go
  pkg/util/labels.go
Labels: size/XL

#898 do not do image lookup when doing dockerfile output build
  pkg/api/describe/describer.go
  pkg/cmd/cli/cmd/build.go
Labels: lgtm, size/S

#899 Improve cross-platform compatibility in generated test script
  examples/nginx-centos7/test/run
  pkg/create/templates/test.go
Labels: size/M
