Repository openshift/source-to-image, pull requests merged in 2018-07, with the labels that each got.

#901 enforce current dir as default working dir
  pkg/build/strategies/dockerfile/dockerfile.go
Labels: size/XS

#906 clarify git clone behavior
  pkg/cmd/cli/cmd/build.go
Labels: approved, lgtm, size/XS

#905 disallow copies to target into the source dir of the copy
  pkg/build/strategies/dockerfile/dockerfile.go
  pkg/scm/downloaders/file/download.go
  pkg/scm/downloaders/file/download_test.go
Labels: lgtm, size/M

#908 Remove references to cli flags in errors
  pkg/build/strategies/dockerfile/dockerfile.go
  pkg/errors/errors.go
  pkg/scm/downloaders/file/download.go
Labels: size/S

#907 Incremental Dockerfile Build
  examples/nginx-centos7/s2i/bin/assemble
  examples/nginx-centos7/s2i/bin/save-artifacts
  pkg/build/strategies/dockerfile/dockerfile.go
  pkg/build/strategies/sti/postexecutorstep.go
  pkg/build/strategies/sti/sti.go
  pkg/cmd/cli/cmd/build.go
  pkg/util/strings.go
  test/integration/integration_test.go
Labels: size/L

#909 update gitignore for vscode, vscode debug, metadata
  .gitignore
Labels: size/XS

#910 build: keep symlinks
  contrib/completions/bash/s2i
  contrib/completions/zsh/s2i
  pkg/api/types.go
  pkg/cmd/cli/cmd/build.go
  pkg/scm/downloaders/file/download.go
  pkg/test/fs/fs.go
  pkg/util/fs/fs.go
  pkg/util/fs/fs_test.go
Labels: size/L

#911 Fix Hang if Injected Dir Does Not Exist
  pkg/build/strategies/sti/sti.go
  pkg/util/injection.go
  pkg/util/injection_test.go
  test/integration/integration_test.go
Labels: size/L
