Repository openshift/source-to-image, pull requests merged in 2018-10, with the labels that each got.

#930 increase timeout on tar extraction and make error clearer
  hack/install-tools.sh
  pkg/tar/tar.go
Labels: size/XS

#931 Clean up the artifacts directory on untar error
  pkg/build/strategies/sti/sti.go
Labels: needs-ok-to-test, size/XS

#938 Fix recursive copy when using --as-dockerfile on non scm-managed folder
  pkg/scm/downloaders/file/download.go
Labels: needs-ok-to-test, size/S

#939 increase timeout for save-artifacts extraction
  .travis.yml
  hack/install-tools.sh
  pkg/build/strategies/sti/sti.go
  pkg/tar/tar.go
Labels: size/S

#940 increase timeout on tar extraction and make error clearer
  .travis.yml
  hack/install-tools.sh
  pkg/build/strategies/sti/sti.go
  pkg/tar/tar.go
Labels: size/S
