Repository openshift/source-to-image, pull requests merged in 2018-09, with the labels that each got.

#924 Update example repos that were moved to sclorg
  README.md
  hack/test-stirunimage.sh
Labels: size/XS

#922 build: only check if docker is reachable when not using --as-dockerfile
  pkg/cmd/cli/cmd/build.go
Labels: needs-ok-to-test, size/S

#925 switch to golang 1.10 for travis
  .travis.yml
Labels: size/XS

#926 URL of OKD is docs.okd.io now
  docs/builder_image.md
  docs/user_guide.md
Labels: size/XS

#927 add add-hosts
  contrib/completions/bash/s2i
  contrib/completions/zsh/s2i
  hack/test-stirunimage.sh
  pkg/api/types.go
  pkg/build/strategies/sti/sti.go
  pkg/cmd/cli/cmd/build.go
  pkg/docker/docker.go
Labels: size/S

#928 use generic iserrnotfound
  pkg/docker/docker.go
Labels: size/XS
