Repository openshift/source-to-image, pull requests merged in 2019-05, with the labels that each got.

#963 Fixes to release process
  hack/build-release.sh
  images/release/Dockerfile
Labels: approved, lgtm, size/S

#965 Make s2i less Docker centric
  README.md
Labels: size/S

#958 Apply .s2iignore during copy from local directory
  pkg/build/strategies/dockerfile/dockerfile.go
  pkg/build/strategies/onbuild/onbuild.go
  pkg/build/strategies/sti/postexecutorstep.go
  pkg/ignore/ignore.go
  pkg/scm/downloaders/file/download.go
  pkg/scm/downloaders/git/clone.go
  pkg/test/fs/fs.go
  pkg/util/fs/fs.go
  pkg/util/fs/fs_test.go
  test/integration/integration_test.go
Labels: lgtm, ok-to-test, size/L
