Repository openshift/source-to-image, pull requests merged in 2019-06, with the labels that each got.

#967 remove basename in main(), the var basename is not used in func CommandFor()
  cmd/s2i/s2i.go
  pkg/cmd/cli/cli.go
Labels: lgtm, size/XS

#975 Refactor s2i Tests for ci-operator
  .travis.yml
  Makefile
  OWNERS
  cmd/doc.go
  hack/test-docker.sh
  hack/test-dockerfile.sh
  hack/test-integration.sh
  hack/verify-govet.sh
  pkg/api/describe/describer.go
  pkg/doc.go
  test/doc.go
  test/integration/docker/doc.go
  test/integration/docker/dockerssl_test.go
  test/integration/docker/integration_test.go
  test/integration/dockerfile/doc.go
  test/integration/dockerfile/dockerfile_test.go
  tools/doc.go
Labels: size/XXL

#976 Bump release golang to 1.12.5
  hack/build-release.sh
  images/release/Dockerfile
Labels: approved, lgtm, size/XS
