Repository openshift/source-to-image, pull requests merged in 2020-10, with the labels that each got.

#1053 Update klog v2
  cmd/s2i/s2i.go
  go.mod
  go.sum
  pkg/cmd/cli/util/util.go
  pkg/scm/downloaders/git/clone.go
  pkg/util/log/log.go
  test/integration/docker/integration_test.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/modules.txt
Labels: approved, lgtm

#1054 Bug 1884270: bypass golang url parsing with scp styled ssh git URLs; refactor URL for older git clients
  pkg/scm/git/url.go
  pkg/scm/git/url_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1055 Use volume mount in release build
  .gitignore
  hack/build-release.sh
  images/release/Dockerfile
Labels: approved, lgtm

#1057 Fix instruction in s2i create README template
  pkg/create/templates/readme.go
Labels: approved, lgtm, ok-to-test
