Repository openshift/source-to-image, pull requests merged in 2020-02, with the labels that each got.

#1020 Bump travis to golang 1.13
  .travis.yml
Labels: approved, lgtm, size/XS

#1019 Allow releases with podman or docker
  hack/build-release.sh
Labels: approved, lgtm, size/S

#1018 Do not propagate URL-like image names to Dockerfile
  pkg/cmd/cli/cmd/generate.go
Labels: approved, lgtm, ok-to-test, size/S

#1022 bump(*): Update transient dependency go-ansiterm
  go.mod
  go.sum
  vendor/github.com/Azure/go-ansiterm/csi_entry_state.go
  vendor/github.com/Azure/go-ansiterm/csi_param_state.go
  vendor/github.com/Azure/go-ansiterm/escape_intermediate_state.go
  vendor/github.com/Azure/go-ansiterm/escape_state.go
  vendor/github.com/Azure/go-ansiterm/osc_string_state.go
  vendor/github.com/Azure/go-ansiterm/parser.go
  vendor/github.com/Azure/go-ansiterm/parser_action_helpers.go
  vendor/github.com/Azure/go-ansiterm/parser_actions.go
  vendor/github.com/Azure/go-ansiterm/winterm/ansi.go
  vendor/github.com/Azure/go-ansiterm/winterm/api.go
  vendor/github.com/Azure/go-ansiterm/winterm/cursor_helpers.go
  vendor/github.com/Azure/go-ansiterm/winterm/scroll_helper.go
  vendor/github.com/Azure/go-ansiterm/winterm/win_event_handler.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/L

#1023 Update documentation for generate and --as-dockerfile
  docs/cli.md
  hack/test-docker.sh
  hack/test-dockerfile.sh
  hack/test-go.sh
  hack/verify-govet.sh
  pkg/cmd/cli/cmd/generate.go
  test/generate_test.go
Labels: approved, lgtm, ok-to-test, size/M
