Repository openshift/source-to-image, pull requests merged in 2023-03, with the labels that each got.

#1105 fix: honor --exclude when using --as-dockerfile
  pkg/scm/downloaders/file/download.go
  pkg/test/fs/fs.go
  pkg/util/fs/fs.go
Labels: approved, lgtm

#1108 Re-enable cross builds for aarch64/arm64
  hack/common.sh
Labels: approved

#1109 adding windows/arm64
  hack/common.sh
Labels: approved

#1111 refactor(fs): simplify CopyContents
  pkg/util/fs/fs.go
Labels: approved, needs-ok-to-test, lgtm

#1112 Generate SHA512SUM for release archives
  hack/common.sh
  pkg/ignore/ignore_test.go
  pkg/util/timeout.go
Labels: approved, lgtm

#1115 A few small fixes
  .ci-operator.yaml
  Dockerfile
  OWNERS
  go.mod
  hack/build-release.sh
Labels: approved, lgtm
